import { readFileSync, statSync } from "node:fs";
import { join } from "node:path";

import Handlebars from "handlebars";

export type TemplateKind = "finding" | "summary";

export interface TemplateContext {
	readonly event?: {
		readonly author?: string;
		readonly url?: string;
		readonly title?: string;
	};
	readonly repo?: {
		readonly name?: string;
		readonly fullName?: string;
	};
	readonly run?: {
		readonly id?: string;
	};
	readonly atMentions?: string;
	readonly findings?: readonly TemplateFinding[];
	readonly summary?: string;
	readonly finding?: TemplateFinding;
}

export interface TemplateFinding {
	readonly file: string;
	readonly line: number;
	readonly endLine?: number;
	readonly severity: string;
	readonly category: string;
	readonly message: string;
	readonly suggestion?: string;
	readonly fingerprint?: string;
	readonly location: string;
}

const BUILTIN_SUMMARY_TEMPLATE = `## AI Code Review Summary

{{#if event.url}}
**PR**: [{{#if event.title}}{{event.title}}]({{event.url}}){{else}}View changes{{/if}}
{{/if}}
{{#if event.author}}
**Author**: @{{event.author}}
{{/if}}
{{#if atMentions}}
**Reviewers**: {{atMentions}}
{{/if}}

---

{{#if summary}}
{{{summary}}}
{{else}}
No summary provided.
{{/if}}

{{#if findings}}
### Findings ({{findings.length}})

| # | Severity | Category | Location | Message |
|---|----------|----------|----------|---------|
{{#each findings}}
| {{@index}} | {{severity}} | {{category}} | \`{{location}}\` | {{message}} |
{{/each}}
{{/if}}

---
*Powered by AICodeReviewer*{{#if run.id}} | Run: {{run.id}}{{/if}}
`;

const BUILTIN_FINDING_TEMPLATE = `**{{finding.severity}} · {{finding.category}}**

{{finding.message}}

Location: \`{{finding.location}}\`
{{#if finding.suggestion}}

**Suggested fix:**

{{finding.suggestion}}
{{/if}}
{{#if finding.fingerprint}}

<!-- aicr:fingerprint={{finding.fingerprint}} -->
{{/if}}
`;

const BUILTIN_GITEA_ISSUE_SUMMARY_TEMPLATE = `## AI Code Review Report

{{#if event.url}}
**Reviewed**: [{{#if event.title}}{{event.title}}]({{event.url}}){{else}}changes{{/if}}
{{/if}}
{{#if event.author}}
**Author**: @{{event.author}}
{{/if}}

---

{{#if summary}}
{{{summary}}}
{{else}}
No summary provided.
{{/if}}

{{#if findings}}
### All Findings ({{findings.length}})

{{#each findings}}
#### {{@index}}. [{{severity}}] {{category}} — \`{{location}}\`

{{message}}
{{#if suggestion}}

> **Suggested fix**: {{suggestion}}
{{/if}}

{{/each}}
{{/if}}

---
*Generated by AICodeReviewer*{{#if run.id}} | Run: {{run.id}}{{/if}}
`;

const BUILTIN_FEISHU_SUMMARY_TEMPLATE = `{{#if event.title}}**{{event.title}}**{{/if}}

{{#if findings}}Findings: {{findings.length}}{{/if}}
{{#if event.url}}
[View PR]({{event.url}})
{{/if}}
{{#if summary}}

{{{summary}}}
{{/if}}
`;

const BUILTIN_WECOM_SUMMARY_TEMPLATE = `{{#if event.title}}{{event.title}}{{/if}}
{{#if findings}}Findings: {{findings.length}}{{/if}}
{{#if event.url}}
{{event.url}}
{{/if}}
{{#if summary}}

{{{summary}}}
{{/if}}
`;

const builtinTemplates: Readonly<Record<string, Record<TemplateKind, string>>> = {
	gitea_pr_review: {
		summary: BUILTIN_SUMMARY_TEMPLATE,
		finding: BUILTIN_FINDING_TEMPLATE,
	},
	gitea_issue: {
		summary: BUILTIN_GITEA_ISSUE_SUMMARY_TEMPLATE,
		finding: BUILTIN_FINDING_TEMPLATE,
	},
	gitea_finding_issue: {
		summary: BUILTIN_GITEA_ISSUE_SUMMARY_TEMPLATE,
		finding: BUILTIN_FINDING_TEMPLATE,
	},
	github_pr_review: {
		summary: BUILTIN_SUMMARY_TEMPLATE,
		finding: BUILTIN_FINDING_TEMPLATE,
	},
	gitlab_mr_review: {
		summary: BUILTIN_SUMMARY_TEMPLATE,
		finding: BUILTIN_FINDING_TEMPLATE,
	},
	feishu_bot: {
		summary: BUILTIN_FEISHU_SUMMARY_TEMPLATE,
		finding: BUILTIN_FINDING_TEMPLATE,
	},
	wecom_bot: {
		summary: BUILTIN_WECOM_SUMMARY_TEMPLATE,
		finding: BUILTIN_FINDING_TEMPLATE,
	},
};

const compiledCache = new Map<string, Handlebars.TemplateDelegate<TemplateContext>>();

function compileTemplate(source: string, cacheKey: string): Handlebars.TemplateDelegate<TemplateContext> {
	const cached = compiledCache.get(cacheKey);
	if (cached) {
		return cached;
	}

	const compiled = Handlebars.compile<TemplateContext>(source, { noEscape: true });
	compiledCache.set(cacheKey, compiled);
	return compiled;
}

export function getBuiltinTemplate(channelKind: string, kind: TemplateKind): string {
	const channelTemplates = builtinTemplates[channelKind];
	if (channelTemplates) {
		return channelTemplates[kind];
	}

	return builtinTemplates["gitea_pr_review"]![kind];
}

export function clearTemplateCache(): void {
	compiledCache.clear();
}

export function renderTemplate(
	source: string,
	context: TemplateContext,
	cacheKey?: string,
): string {
	const key = cacheKey ?? source;
	const compiled = compileTemplate(source, key);
	return compiled(context);
}

export function renderBuiltinTemplate(
	channelKind: string,
	kind: TemplateKind,
	context: TemplateContext,
): string {
	const source = getBuiltinTemplate(channelKind, kind);
	return renderTemplate(source, context, `builtin:${channelKind}:${kind}`);
}

export function toTemplateFinding(finding: {
	readonly file: string;
	readonly line: number;
	readonly endLine?: number;
	readonly severity: string;
	readonly category: string;
	readonly message: string;
	readonly suggestion?: string;
	readonly fingerprint?: string;
}): TemplateFinding {
	return {
		file: finding.file,
		line: finding.line,
		...(finding.endLine !== undefined ? { endLine: finding.endLine } : {}),
		severity: finding.severity.toUpperCase(),
		category: finding.category,
		message: finding.message,
		...(finding.suggestion ? { suggestion: finding.suggestion } : {}),
		...(finding.fingerprint ? { fingerprint: finding.fingerprint } : {}),
		location: finding.endLine
			? `${finding.file}:${finding.line}-${finding.endLine}`
			: `${finding.file}:${finding.line}`,
	};
}

export interface TemplateResolverOptions {
	readonly channelKind: string;
	readonly channelName?: string;
	readonly workspaceTemplatesDir?: string;
}

export interface TemplateResolver {
	readonly resolveTemplate: (kind: TemplateKind) => string;
	readonly render: (kind: TemplateKind, context: TemplateContext) => string;
}

interface ResolvedTemplateSource {
	readonly source: string;
	readonly cacheKey: string;
}

function isMissingFileError(error: unknown): boolean {
	return typeof error === "object" &&
		error !== null &&
		"code" in error &&
		((error as { readonly code?: unknown }).code === "ENOENT" ||
			(error as { readonly code?: unknown }).code === "ENOTDIR");
}

function workspaceTemplateCandidates(options: TemplateResolverOptions, kind: TemplateKind): string[] {
	const candidates: string[] = [];
	if (options.channelName) {
		candidates.push(`${options.channelName}.${kind}.md.hbs`, `${options.channelName}.${kind}.hbs`);
	}

	candidates.push(
		`${options.channelKind}.${kind}.md.hbs`,
		`${options.channelKind}.${kind}.hbs`,
		`${kind}.md.hbs`,
		`${kind}.hbs`,
	);

	return candidates;
}

function resolveWorkspaceTemplate(
	options: TemplateResolverOptions,
	kind: TemplateKind,
): ResolvedTemplateSource | undefined {
	if (!options.workspaceTemplatesDir) {
		return undefined;
	}

	for (const candidate of workspaceTemplateCandidates(options, kind)) {
		const templatePath = join(options.workspaceTemplatesDir, candidate);
		try {
			const stat = statSync(templatePath);
			if (!stat.isFile()) {
				continue;
			}

			return {
				source: readFileSync(templatePath, "utf8"),
				cacheKey: `workspace:${templatePath}:${stat.mtimeMs}`,
			};
		} catch (error) {
			if (isMissingFileError(error)) {
				continue;
			}

			throw error;
		}
	}

	return undefined;
}

function resolveTemplateSource(options: TemplateResolverOptions, kind: TemplateKind): ResolvedTemplateSource {
	const workspaceTemplate = resolveWorkspaceTemplate(options, kind);
	if (workspaceTemplate) {
		return workspaceTemplate;
	}

	return {
		source: getBuiltinTemplate(options.channelKind, kind),
		cacheKey: `builtin:${options.channelKind}:${kind}`,
	};
}

export function createTemplateResolver(options: TemplateResolverOptions): TemplateResolver {
	return {
		resolveTemplate(kind: TemplateKind): string {
			return resolveTemplateSource(options, kind).source;
		},

		render(kind: TemplateKind, context: TemplateContext): string {
			const resolved = resolveTemplateSource(options, kind);
			return renderTemplate(resolved.source, context, resolved.cacheKey);
		},
	};
}
