import { readFileSync, statSync } from "node:fs";
import { join } from "node:path";

import Handlebars from "handlebars";

type PrimaryTemplateKind = "problem" | "summary";

export type TemplateKind = PrimaryTemplateKind | "finding";

export interface TemplateContext {
	readonly event?: {
		readonly author?: string;
		readonly url?: string;
		readonly title?: string;
	};
	readonly repo?: {
		readonly name?: string;
		readonly fullName?: string;
	};
	readonly run?: {
		readonly id?: string;
	};
	readonly atMentions?: string;
	readonly problems?: readonly TemplateProblem[];
	readonly problem?: TemplateProblem;
	/** @deprecated Use problems. */
	readonly findings?: readonly TemplateProblem[];
	readonly summary?: string;
	/** @deprecated Use problem. */
	readonly finding?: TemplateProblem;
}

export interface TemplateProblem {
	readonly file: string;
	readonly line: number;
	readonly endLine?: number;
	readonly severity: string;
	readonly category: string;
	readonly message: string;
	readonly suggestion?: string;
	readonly fingerprint?: string;
	readonly location: string;
}

const BUILTIN_SUMMARY_TEMPLATE = `## AI Code Review Summary

{{#if event.url}}
**PR**: [{{#if event.title}}{{event.title}}]({{event.url}}){{else}}View changes{{/if}}
{{/if}}
{{#if event.author}}
**Author**: @{{event.author}}
{{/if}}
{{#if atMentions}}
**Reviewers**: {{atMentions}}
{{/if}}

---

{{#if summary}}
{{{summary}}}
{{else}}
No summary provided.
{{/if}}

{{#if problems}}
### Problems ({{problems.length}})

| # | Severity | Category | Location | Message |
|---|----------|----------|----------|---------|
{{#each problems}}
| {{@index}} | {{severity}} | {{category}} | \`{{location}}\` | {{message}} |
{{/each}}
{{/if}}

---
*Powered by AICodeReviewer*{{#if run.id}} | Run: {{run.id}}{{/if}}
`;

const BUILTIN_PROBLEM_TEMPLATE = `**{{problem.severity}} · {{problem.category}}**

{{problem.message}}

Location: \`{{problem.location}}\`
{{#if problem.suggestion}}

**Suggested fix:**

{{problem.suggestion}}
{{/if}}
{{#if problem.fingerprint}}

<!-- aicr:fingerprint={{problem.fingerprint}} -->
{{/if}}
`;

const BUILTIN_GITEA_ISSUE_SUMMARY_TEMPLATE = `## AI Code Review Report

{{#if event.url}}
**Reviewed**: [{{#if event.title}}{{event.title}}]({{event.url}}){{else}}changes{{/if}}
{{/if}}
{{#if event.author}}
**Author**: @{{event.author}}
{{/if}}

---

{{#if summary}}
{{{summary}}}
{{else}}
No summary provided.
{{/if}}

{{#if problems}}
### All Problems ({{problems.length}})

{{#each problems}}
#### {{@index}}. [{{severity}}] {{category}} — \`{{location}}\`

{{message}}
{{#if suggestion}}

> **Suggested fix**: {{suggestion}}
{{/if}}

{{/each}}
{{/if}}

---
*Generated by AICodeReviewer*{{#if run.id}} | Run: {{run.id}}{{/if}}
`;

const BUILTIN_FEISHU_SUMMARY_TEMPLATE = `{{#if event.title}}**{{event.title}}**{{/if}}

{{#if problems}}Problems: {{problems.length}}{{/if}}
{{#if event.url}}
[View changes]({{event.url}})
{{/if}}
{{#if summary}}

{{{summary}}}
{{/if}}
`;

const BUILTIN_WECOM_SUMMARY_TEMPLATE = `{{#if event.title}}{{event.title}}{{/if}}
{{#if problems}}Problems: {{problems.length}}{{/if}}
{{#if event.url}}
{{event.url}}
{{/if}}
{{#if summary}}

{{{summary}}}
{{/if}}
`;

const builtinTemplates: Readonly<Record<string, Record<PrimaryTemplateKind, string>>> = {
	gitea_pr_review: {
		summary: BUILTIN_SUMMARY_TEMPLATE,
		problem: BUILTIN_PROBLEM_TEMPLATE,
	},
	gitea_issue: {
		summary: BUILTIN_GITEA_ISSUE_SUMMARY_TEMPLATE,
		problem: BUILTIN_PROBLEM_TEMPLATE,
	},
	gitea_problem_issue: {
		summary: BUILTIN_GITEA_ISSUE_SUMMARY_TEMPLATE,
		problem: BUILTIN_PROBLEM_TEMPLATE,
	},
	gitea_finding_issue: {
		summary: BUILTIN_GITEA_ISSUE_SUMMARY_TEMPLATE,
		problem: BUILTIN_PROBLEM_TEMPLATE,
	},
	github_pr_review: {
		summary: BUILTIN_SUMMARY_TEMPLATE,
		problem: BUILTIN_PROBLEM_TEMPLATE,
	},
	gitlab_mr_review: {
		summary: BUILTIN_SUMMARY_TEMPLATE,
		problem: BUILTIN_PROBLEM_TEMPLATE,
	},
	feishu_bot: {
		summary: BUILTIN_FEISHU_SUMMARY_TEMPLATE,
		problem: BUILTIN_PROBLEM_TEMPLATE,
	},
	wecom_bot: {
		summary: BUILTIN_WECOM_SUMMARY_TEMPLATE,
		problem: BUILTIN_PROBLEM_TEMPLATE,
	},
};

const compiledCache = new Map<string, Handlebars.TemplateDelegate<TemplateContext>>();

function compileTemplate(source: string, cacheKey: string): Handlebars.TemplateDelegate<TemplateContext> {
	const cached = compiledCache.get(cacheKey);
	if (cached) {
		return cached;
	}

	const compiled = Handlebars.compile<TemplateContext>(source, { noEscape: true });
	compiledCache.set(cacheKey, compiled);
	return compiled;
}

function normalizeTemplateKind(kind: TemplateKind): PrimaryTemplateKind {
	return kind === "finding" ? "problem" : kind;
}

function withTemplateAliases(context: TemplateContext): TemplateContext {
	const problems = context.problems ?? context.findings;
	const problem = context.problem ?? context.finding;
	return {
		...context,
		...(problems ? { problems, findings: problems } : {}),
		...(problem ? { problem, finding: problem } : {}),
	};
}

export function getBuiltinTemplate(channelKind: string, kind: TemplateKind): string {
	const normalizedKind = normalizeTemplateKind(kind);
	const channelTemplates = builtinTemplates[channelKind];
	if (channelTemplates) {
		return channelTemplates[normalizedKind];
	}

	return builtinTemplates["gitea_pr_review"]![normalizedKind];
}

export function clearTemplateCache(): void {
	compiledCache.clear();
}

export function renderTemplate(
	source: string,
	context: TemplateContext,
	cacheKey?: string,
): string {
	const key = cacheKey ?? source;
	const compiled = compileTemplate(source, key);
	return compiled(withTemplateAliases(context));
}

export function renderBuiltinTemplate(
	channelKind: string,
	kind: TemplateKind,
	context: TemplateContext,
): string {
	const source = getBuiltinTemplate(channelKind, kind);
	return renderTemplate(source, context, `builtin:${channelKind}:${kind}`);
}

export function toTemplateProblem(problem: {
	readonly file: string;
	readonly line: number;
	readonly endLine?: number;
	readonly severity: string;
	readonly category: string;
	readonly message: string;
	readonly suggestion?: string;
	readonly fingerprint?: string;
}): TemplateProblem {
	return {
		file: problem.file,
		line: problem.line,
		...(problem.endLine !== undefined ? { endLine: problem.endLine } : {}),
		severity: problem.severity.toUpperCase(),
		category: problem.category,
		message: problem.message,
		...(problem.suggestion ? { suggestion: problem.suggestion } : {}),
		...(problem.fingerprint ? { fingerprint: problem.fingerprint } : {}),
		location: problem.endLine
			? `${problem.file}:${problem.line}-${problem.endLine}`
			: `${problem.file}:${problem.line}`,
	};
}

export interface TemplateResolverOptions {
	readonly channelKind: string;
	readonly channelName?: string;
	readonly workspaceTemplatesDir?: string;
}

export interface TemplateResolver {
	readonly resolveTemplate: (kind: TemplateKind) => string;
	readonly render: (kind: TemplateKind, context: TemplateContext) => string;
}

interface ResolvedTemplateSource {
	readonly source: string;
	readonly cacheKey: string;
}

function isMissingFileError(error: unknown): boolean {
	return typeof error === "object" &&
		error !== null &&
		"code" in error &&
		((error as { readonly code?: unknown }).code === "ENOENT" ||
			(error as { readonly code?: unknown }).code === "ENOTDIR");
}

function workspaceTemplateCandidates(options: TemplateResolverOptions, kind: TemplateKind): string[] {
	const candidates: string[] = [];
	const normalizedKind = normalizeTemplateKind(kind);
	const kinds = normalizedKind === "problem" ? ["problem", "finding"] : [normalizedKind];
	if (options.channelName) {
		for (const candidateKind of kinds) {
			candidates.push(`${options.channelName}.${candidateKind}.md.hbs`, `${options.channelName}.${candidateKind}.hbs`);
		}
	}

	for (const candidateKind of kinds) {
		candidates.push(
			`${options.channelKind}.${candidateKind}.md.hbs`,
			`${options.channelKind}.${candidateKind}.hbs`,
			`${candidateKind}.md.hbs`,
			`${candidateKind}.hbs`,
		);
	}

	return candidates;
}

function resolveWorkspaceTemplate(
	options: TemplateResolverOptions,
	kind: TemplateKind,
): ResolvedTemplateSource | undefined {
	if (!options.workspaceTemplatesDir) {
		return undefined;
	}

	for (const candidate of workspaceTemplateCandidates(options, kind)) {
		const templatePath = join(options.workspaceTemplatesDir, candidate);
		try {
			const stat = statSync(templatePath);
			if (!stat.isFile()) {
				continue;
			}

			return {
				source: readFileSync(templatePath, "utf8"),
				cacheKey: `workspace:${templatePath}:${stat.mtimeMs}`,
			};
		} catch (error) {
			if (isMissingFileError(error)) {
				continue;
			}

			throw error;
		}
	}

	return undefined;
}

function resolveTemplateSource(options: TemplateResolverOptions, kind: TemplateKind): ResolvedTemplateSource {
	const normalizedKind = normalizeTemplateKind(kind);
	const workspaceTemplate = resolveWorkspaceTemplate(options, kind);
	if (workspaceTemplate) {
		return workspaceTemplate;
	}

	return {
		source: getBuiltinTemplate(options.channelKind, normalizedKind),
		cacheKey: `builtin:${options.channelKind}:${normalizedKind}`,
	};
}

export function createTemplateResolver(options: TemplateResolverOptions): TemplateResolver {
	return {
		resolveTemplate(kind: TemplateKind): string {
			return resolveTemplateSource(options, kind).source;
		},

		render(kind: TemplateKind, context: TemplateContext): string {
			const resolved = resolveTemplateSource(options, kind);
			return renderTemplate(resolved.source, context, resolved.cacheKey);
		},
	};
}
