import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { ModelSpec } from "@aicr/llm";

import {
  buildPiFamilyEnvVars,
  buildPiFamilyProviderConfig,
  formatPiFamilyModel,
  resolvePiFamilyThinking,
} from "./pi-family.js";
import type {
  AgentAdapter,
  AgentDetectResult,
  AgentKind,
  AgentMaterializeOptions,
  AgentMaterializeResult,
  AgentSpawnOptions,
} from "./types.js";

export interface OhMyPiAdapterOptions {
  readonly binary?: string;
}

const OMP_BINARY = "omp";
const OMP_VERSION_ARGS = ["--version"];

/** Bundle-relative config dir; PI_CODING_AGENT_DIR points here inside the sandbox. */
export const OMP_AGENT_DIR_NAME = ".omp-agent";
export const OMP_MCP_CONFIG_PATH = `${OMP_AGENT_DIR_NAME}/mcp.json`;

async function detectBinary(binary: string, versionArgs: readonly string[]): Promise<AgentDetectResult> {
  const { execFile } = await import("node:child_process");
  const { promisify } = await import("node:util");
  const execFileAsync = promisify(execFile);

  try {
    const result = await execFileAsync(binary, versionArgs as string[], {
      timeout: 10_000,
      windowsHide: true,
    });
    const trimmed = result.stdout.trim();
    return { available: true, binary, ...(trimmed ? { version: trimmed } : {}) };
  } catch {
    return { available: false, binary };
  }
}

/** JSON.stringify yields a valid YAML double-quoted scalar. */
function yq(value: string): string {
  return JSON.stringify(value);
}

function buildOmpModelsYaml(model: ModelSpec): string {
  const provider = buildPiFamilyProviderConfig(model, "oh-my-pi");
  const entry = provider.modelEntry;
  const cost = entry.cost as Record<string, number>;
  const input = entry.input as readonly string[];
  const lines: string[] = [
    "# Generated by AICR materializeRuntimeBundle; do not edit.",
    "providers:",
    `  ${yq(model.providerId)}:`,
    `    baseUrl: ${yq(provider.baseUrl)}`,
    `    api: ${yq(provider.api)}`,
  ];
  if (provider.apiKey) {
    // omp resolves the apiKey value as an env-var name first, then as a literal;
    // writing the env name keeps secrets out of the bundle.
    lines.push(`    apiKey: ${yq(provider.apiKey)}`);
  } else {
    lines.push(`    auth: ${yq("none")}`);
  }
  if (provider.headers) {
    lines.push("    headers:");
    for (const [key, value] of Object.entries(provider.headers)) {
      lines.push(`      ${yq(key)}: ${yq(value)}`);
    }
  }
  lines.push(
    "    models:",
    `      - id: ${yq(model.modelId)}`,
    `        name: ${yq(String(entry.name))}`,
    `        reasoning: ${entry.reasoning === true ? "true" : "false"}`,
    `        input: [${input.map(yq).join(", ")}]`,
    "        cost:",
    `          input: ${cost.input}`,
    `          output: ${cost.output}`,
    `          cacheRead: ${cost.cacheRead}`,
    `          cacheWrite: ${cost.cacheWrite}`,
    `        contextWindow: ${entry.contextWindow}`,
    `        maxTokens: ${entry.maxTokens}`,
  );
  return `${lines.join("\n")}\n`;
}

function buildOmpConfigYaml(options?: AgentMaterializeOptions): string {
  const lines: string[] = ["# Generated by AICR materializeRuntimeBundle; do not edit."];
  if (options?.compaction) {
    lines.push("compaction:", `  enabled: ${options.compaction.auto ? "true" : "false"}`);
    if (options.compaction.thresholdPercent !== undefined) {
      lines.push(`  thresholdPercent: ${options.compaction.thresholdPercent}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

export function createOhMyPiAdapter(options: OhMyPiAdapterOptions = {}): AgentAdapter {
  const binary = options.binary ?? OMP_BINARY;

  return {
    kind: "oh-my-pi" as AgentKind,

    async detect(): Promise<AgentDetectResult> {
      return detectBinary(binary, OMP_VERSION_ARGS);
    },

    buildCommand(task: string, spawnOptions: AgentSpawnOptions): readonly string[] {
      const args: string[] = [binary, "-p", "--mode", "json", "--auto-approve", "--no-session"];
      if (spawnOptions.model) {
        args.push("--model", formatPiFamilyModel(spawnOptions.model));
        const thinking = resolvePiFamilyThinking(spawnOptions.model);
        if (thinking) {
          args.push("--thinking", thinking);
        }
      }
      args.push("--", task);
      return args;
    },

    buildStdin(): string {
      return "";
    },

    async materializeConfig(
      model: ModelSpec,
      workingDir: string,
      materializeOptions?: AgentMaterializeOptions,
    ): Promise<AgentMaterializeResult> {
      const agentDir = join(workingDir, OMP_AGENT_DIR_NAME);
      await mkdir(agentDir, { recursive: true });

      const modelsYaml = buildOmpModelsYaml(model);
      const configYaml = buildOmpConfigYaml(materializeOptions);
      await writeFile(join(agentDir, "models.yml"), modelsYaml, "utf8");
      await writeFile(join(agentDir, "config.yml"), configYaml, "utf8");

      return {
        configFiles: new Map([
          [`${OMP_AGENT_DIR_NAME}/models.yml`, modelsYaml],
          [`${OMP_AGENT_DIR_NAME}/config.yml`, configYaml],
        ]),
        envVars: buildPiFamilyEnvVars(model),
        workingDir,
      };
    },
  };
}
