import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { ModelSpec } from "@aicr/llm";

import {
  buildPiFamilyEnvVars,
  buildPiFamilyProviderConfig,
  formatPiFamilyModel,
  resolvePiFamilyThinking,
} from "./pi-family.js";
import type {
  AgentAdapter,
  AgentDetectResult,
  AgentKind,
  AgentMaterializeOptions,
  AgentMaterializeResult,
  AgentSpawnOptions,
  AgentWebSearchOptions,
} from "./types.js";

export interface OhMyPiAdapterOptions {
  readonly binary?: string;
}

const OMP_BINARY = "omp";
const OMP_VERSION_ARGS = ["--version"];

/** Bundle-relative config dir; PI_CODING_AGENT_DIR points here inside the sandbox. */
export const OMP_AGENT_DIR_NAME = ".omp-agent";
export const OMP_MCP_CONFIG_PATH = `${OMP_AGENT_DIR_NAME}/mcp.json`;

/**
 * omp-native env var names for web-search credential providers, verified against
 * omp 18.0.6 (`docs/tools/web_search.md`, `docs/environment-variables.md`, plus
 * binary string scan). Keep in sync with `agentWebSearchCredentialProviderSchema`
 * in `packages/core/src/config.ts`. OAuth-stored providers (perplexity/gemini/
 * codex OAuth) have no env-keyed path usable inside the ephemeral
 * `PI_CODING_AGENT_DIR` bundle and are intentionally absent.
 */
export const OMP_WEB_SEARCH_CREDENTIAL_ENV_NAMES: Readonly<Record<string, string>> = {
  tavily: "TAVILY_API_KEY",
  brave: "BRAVE_API_KEY",
  exa: "EXA_API_KEY",
  jina: "JINA_API_KEY",
  kagi: "KAGI_API_KEY",
  parallel: "PARALLEL_API_KEY",
  kimi: "KIMI_SEARCH_API_KEY",
  perplexity: "PERPLEXITY_API_KEY",
  zai: "ZAI_API_KEY",
  xai: "XAI_API_KEY",
  anthropic: "ANTHROPIC_SEARCH_API_KEY",
  tinyfish: "TINYFISH_API_KEY",
  firecrawl: "FIRECRAWL_API_KEY",
  searxng_token: "SEARXNG_TOKEN",
  searxng_basic_username: "SEARXNG_BASIC_USERNAME",
  searxng_basic_password: "SEARXNG_BASIC_PASSWORD",
};

/**
 * Maps AICR-side credential env names onto omp-native env names as `${VAR}`
 * references resolved by the orchestrator at spawn time. Mirrors the pi-family
 * apiKey pattern: the bundle only ever records env var names, never secrets.
 */
export function buildOmpWebSearchEnvVars(webSearch?: AgentWebSearchOptions): Record<string, string> {
  if (!webSearch?.enabled) return {};
  const credentials = webSearch?.credentials;
  if (!credentials) return {};
  const envVars: Record<string, string> = {};
  for (const [provider, envName] of Object.entries(credentials)) {
    const nativeEnvName = OMP_WEB_SEARCH_CREDENTIAL_ENV_NAMES[provider];
    if (!nativeEnvName) {
      throw new RangeError(
        `Agent oh-my-pi web search credential provider "${provider}" is not supported ` +
          `(supported: ${Object.keys(OMP_WEB_SEARCH_CREDENTIAL_ENV_NAMES).join(", ")}).`,
      );
    }
    envVars[nativeEnvName] = `\${${envName}}`;
  }
  return envVars;
}

async function detectBinary(binary: string, versionArgs: readonly string[]): Promise<AgentDetectResult> {
  const { execFile } = await import("node:child_process");
  const { promisify } = await import("node:util");
  const execFileAsync = promisify(execFile);

  try {
    const result = await execFileAsync(binary, versionArgs as string[], {
      timeout: 10_000,
      windowsHide: true,
    });
    const trimmed = result.stdout.trim();
    return { available: true, binary, ...(trimmed ? { version: trimmed } : {}) };
  } catch {
    return { available: false, binary };
  }
}

/** JSON.stringify yields a valid YAML double-quoted scalar. */
function yq(value: string): string {
  return JSON.stringify(value);
}

function buildOmpModelsYaml(model: ModelSpec): string {
  const provider = buildPiFamilyProviderConfig(model, "oh-my-pi");
  const entry = provider.modelEntry;
  const cost = entry.cost as Record<string, number>;
  const input = entry.input as readonly string[];
  const lines: string[] = [
    "# Generated by AICR materializeRuntimeBundle; do not edit.",
    "providers:",
    `  ${yq(model.providerId)}:`,
    `    baseUrl: ${yq(provider.baseUrl)}`,
    `    api: ${yq(provider.api)}`,
  ];
  if (provider.apiKey) {
    // omp resolves the apiKey value as an env-var name first, then as a literal;
    // writing the env name keeps secrets out of the bundle.
    lines.push(`    apiKey: ${yq(provider.apiKey)}`);
  } else {
    lines.push(`    auth: ${yq("none")}`);
  }
  if (provider.headers) {
    lines.push("    headers:");
    for (const [key, value] of Object.entries(provider.headers)) {
      lines.push(`      ${yq(key)}: ${yq(value)}`);
    }
  }
  lines.push(
    "    models:",
    `      - id: ${yq(model.modelId)}`,
    `        name: ${yq(String(entry.name))}`,
    `        reasoning: ${entry.reasoning === true ? "true" : "false"}`,
    `        input: [${input.map(yq).join(", ")}]`,
    "        cost:",
    `          input: ${cost.input}`,
    `          output: ${cost.output}`,
    `          cacheRead: ${cost.cacheRead}`,
    `          cacheWrite: ${cost.cacheWrite}`,
    `        contextWindow: ${entry.contextWindow}`,
    `        maxTokens: ${entry.maxTokens}`,
  );
  return `${lines.join("\n")}\n`;
}

function buildOmpConfigYaml(options?: AgentMaterializeOptions): string {
  const lines: string[] = ["# Generated by AICR materializeRuntimeBundle; do not edit."];
  const webSearch = options?.webSearch;
  if (webSearch) {
    // omp enables its built-in web_search tool by default (verified omp 18.0.6);
    // AICR always writes the explicit switch so hermetic reviews stay disabled and
    // opt-in runs get the operator's bounded provider chain.
    lines.push("web_search:", `  enabled: ${webSearch.enabled ? "true" : "false"}`);
    const providerLines: string[] = [];
    if (webSearch.providers !== undefined && webSearch.providers.length > 0) {
      providerLines.push(`  webSearchOrder: [${webSearch.providers.map(yq).join(", ")}]`);
    }
    if (webSearch.exclude !== undefined && webSearch.exclude.length > 0) {
      providerLines.push(`  webSearchExclude: [${webSearch.exclude.map(yq).join(", ")}]`);
    }
    if (webSearch.timeoutSeconds !== undefined) {
      providerLines.push(`  webSearchTimeoutSeconds: ${webSearch.timeoutSeconds}`);
    }
    if (providerLines.length > 0) {
      lines.push("providers:", ...providerLines);
    }
    const searxng = webSearch.searxng;
    if (searxng) {
      const searxngLines = [
        ...(searxng.endpoint !== undefined ? [`  endpoint: ${yq(searxng.endpoint)}`] : []),
        ...(searxng.categories !== undefined ? [`  categories: ${yq(searxng.categories)}`] : []),
        ...(searxng.engines !== undefined ? [`  engines: ${yq(searxng.engines)}`] : []),
        ...(searxng.language !== undefined ? [`  language: ${yq(searxng.language)}`] : []),
        ...(searxng.safesearch !== undefined ? [`  safesearch: ${searxng.safesearch}`] : []),
      ];
      if (searxngLines.length > 0) {
        lines.push("searxng:", ...searxngLines);
      }
    }
  }
  if (options?.compaction) {
    lines.push("compaction:", `  enabled: ${options.compaction.auto ? "true" : "false"}`);
    if (options.compaction.thresholdPercent !== undefined) {
      lines.push(`  thresholdPercent: ${options.compaction.thresholdPercent}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

export function createOhMyPiAdapter(options: OhMyPiAdapterOptions = {}): AgentAdapter {
  const binary = options.binary ?? OMP_BINARY;

  return {
    kind: "oh-my-pi" as AgentKind,

    // The task is one positional argv string (`-- <task>`).
    taskTransport: "argv",

    async detect(): Promise<AgentDetectResult> {
      return detectBinary(binary, OMP_VERSION_ARGS);
    },

    buildCommand(task: string, spawnOptions: AgentSpawnOptions): readonly string[] {
      const args: string[] = [binary, "-p", "--mode", "json", "--auto-approve", "--no-session"];
      if (spawnOptions.model) {
        args.push("--model", formatPiFamilyModel(spawnOptions.model));
        const thinking = resolvePiFamilyThinking(spawnOptions.model);
        if (thinking) {
          args.push("--thinking", thinking);
        }
      }
      args.push("--", task);
      return args;
    },

    buildStdin(): string {
      return "";
    },

    async materializeConfig(
      model: ModelSpec,
      workingDir: string,
      materializeOptions?: AgentMaterializeOptions,
    ): Promise<AgentMaterializeResult> {
      const agentDir = join(workingDir, OMP_AGENT_DIR_NAME);
      await mkdir(agentDir, { recursive: true });

      const modelsYaml = buildOmpModelsYaml(model);
      const configYaml = buildOmpConfigYaml(materializeOptions);
      await writeFile(join(agentDir, "models.yml"), modelsYaml, "utf8");
      await writeFile(join(agentDir, "config.yml"), configYaml, "utf8");

      return {
        configFiles: new Map([
          [`${OMP_AGENT_DIR_NAME}/models.yml`, modelsYaml],
          [`${OMP_AGENT_DIR_NAME}/config.yml`, configYaml],
        ]),
        envVars: {
          ...buildPiFamilyEnvVars(model),
          ...buildOmpWebSearchEnvVars(materializeOptions?.webSearch),
        },
        workingDir,
      };
    },
  };
}
