/**
 * Renders the pi extension that bridges AICR's MCP stdio servers into pi tools.
 *
 * pi has no built-in MCP client (an explicit upstream design decision); the
 * documented integration path is a TypeScript extension. The generated file lives
 * at `<PI_CODING_AGENT_DIR>/extensions/aicr-output.ts`, a user-level location that
 * loads without project trust, and pi awaits async extension factories before the
 * first model call, so bridged tools are registered before turn one.
 *
 * Tool names are exposed as `pi_<server>_<tool>` (sanitized to [A-Za-z0-9_]), which
 * the orchestrator's normalizeToolName maps back to canonical `aicr.*` names via the
 * existing `<prefix>_aicr_<tool>` rule. Server specs arrive via the
 * AICR_PI_MCP_SERVERS env var so no command paths or state paths are baked in.
 */
export function renderPiMcpBridgeExtension(): string {
  return BRIDGE_SOURCE;
}

const BRIDGE_SOURCE = `// Generated by AICR (packages/agents/src/pi-mcp-bridge.ts); do not edit.
// Bridges AICR MCP stdio servers into pi as extension-registered tools.

import { spawn } from "node:child_process";
import { Type } from "typebox";

const SERVERS_ENV = "AICR_PI_MCP_SERVERS";
const PROTOCOL_VERSION = "2025-06-18";
const HANDSHAKE_TIMEOUT_MS = 15000;
const CALL_TIMEOUT_MS = 120000;
const MAX_BUFFER_BYTES = 16 * 1024 * 1024;
const BASE_ENV_KEYS = ["PATH", "Path", "SYSTEMROOT", "SystemRoot", "HOME", "TMPDIR", "TEMP", "TMP"];

// Only the minimal runtime base env plus the per-server spec environment reaches
// MCP children; the agent process env (which carries the resolved provider API
// key) must not leak into spawned servers.
function buildChildEnv(extra) {
  const base = {};
  for (const key of BASE_ENV_KEYS) {
    if (typeof process.env[key] === "string") {
      base[key] = process.env[key];
    }
  }
  return Object.assign(base, extra || {});
}

function logBridgeError(...args) {
  console.error("[aicr-output-bridge]", ...args);
}

function sanitizeComponent(value) {
  return String(value).replace(/[^A-Za-z0-9_]/g, "_");
}

function bridgeToolName(serverName, toolName) {
  return "pi_" + sanitizeComponent(serverName) + "_" + sanitizeComponent(toolName);
}

class StdioMcpClient {
  constructor(spec) {
    this.spec = spec;
    this.nextId = 1;
    this.buffer = "";
    this.pending = new Map();
    this.failed = null;
    this.child = spawn(spec.command[0], spec.command.slice(1), {
      env: buildChildEnv(spec.environment),
      stdio: ["pipe", "pipe", "inherit"],
      windowsHide: true,
    });
    this.child.stdout.setEncoding("utf8");
    this.child.stdout.on("data", (chunk) => this.onData(chunk));
    this.child.on("error", (err) => this.failAll(err));
    this.child.on("exit", (code, signal) => {
      this.failAll(new Error("MCP server " + this.spec.name + " exited (code=" + code + ", signal=" + signal + ")"));
    });
  }

  onData(chunk) {
    if (this.failed) {
      return;
    }
    this.buffer += chunk;
    if (this.buffer.length > MAX_BUFFER_BYTES) {
      this.failAll(new Error("MCP server " + this.spec.name + " exceeded the maximum message buffer"));
      this.dispose();
      return;
    }
    let index = this.buffer.indexOf("\\n");
    while (index >= 0) {
      const line = this.buffer.slice(0, index).trim();
      this.buffer = this.buffer.slice(index + 1);
      index = this.buffer.indexOf("\\n");
      if (!line) {
        continue;
      }
      let message;
      try {
        message = JSON.parse(line);
      } catch {
        continue;
      }
      if (message && typeof message.id === "number" && this.pending.has(message.id)) {
        const entry = this.pending.get(message.id);
        this.pending.delete(message.id);
        clearTimeout(entry.timer);
        if (message.error) {
          entry.reject(new Error("MCP error " + JSON.stringify(message.error)));
        } else {
          entry.resolve(message.result);
        }
      }
    }
  }

  failAll(error) {
    if (!this.failed) {
      this.failed = error;
    }
    for (const entry of this.pending.values()) {
      clearTimeout(entry.timer);
      entry.reject(this.failed);
    }
    this.pending.clear();
  }

  request(method, params, timeoutMs) {
    if (this.failed) {
      return Promise.reject(this.failed);
    }
    const id = this.nextId;
    this.nextId += 1;
    const payload = JSON.stringify({ jsonrpc: "2.0", id, method, params: params || {} });
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error("MCP request " + method + " timed out after " + timeoutMs + "ms"));
      }, timeoutMs);
      this.pending.set(id, { resolve, reject, timer });
      try {
        this.child.stdin.write(payload + "\\n");
      } catch (error) {
        clearTimeout(timer);
        this.pending.delete(id);
        reject(error);
      }
    });
  }

  notify(method, params) {
    try {
      this.child.stdin.write(JSON.stringify({ jsonrpc: "2.0", method, params: params || {} }) + "\\n");
    } catch {
      // Server already gone; the exit handler surfaces the failure.
    }
  }

  async initialize() {
    await this.request("initialize", {
      protocolVersion: PROTOCOL_VERSION,
      capabilities: {},
      clientInfo: { name: "aicr-pi-bridge", version: "1.0.0" },
    }, HANDSHAKE_TIMEOUT_MS);
    this.notify("notifications/initialized");
  }

  async listTools() {
    const result = await this.request("tools/list", {}, HANDSHAKE_TIMEOUT_MS);
    return result && Array.isArray(result.tools) ? result.tools : [];
  }

  async callTool(name, args) {
    return this.request("tools/call", { name, arguments: args || {} }, CALL_TIMEOUT_MS);
  }

  dispose() {
    try {
      this.child.kill();
    } catch {
      // Best-effort cleanup only.
    }
  }
}

function toToolResultText(result) {
  const content = result && Array.isArray(result.content) ? result.content : [];
  const text = content
    .map((part) => (part && part.type === "text" && typeof part.text === "string" ? part.text : JSON.stringify(part)))
    .join("\\n");
  return text.length > 0 ? text : JSON.stringify(result === undefined ? null : result);
}

export default async function aicrOutputBridge(pi) {
  const raw = process.env[SERVERS_ENV];
  if (!raw) {
    return;
  }
  let specs;
  try {
    specs = JSON.parse(raw);
  } catch (error) {
    logBridgeError("invalid server spec JSON:", error);
    return;
  }
  if (!Array.isArray(specs) || specs.length === 0) {
    return;
  }

  const clients = [];
  const killAll = () => {
    for (const client of clients) {
      client.dispose();
    }
  };
  pi.on("session_shutdown", killAll);
  process.on("exit", killAll);

  for (const spec of specs) {
    if (!spec || !Array.isArray(spec.command) || spec.command.length === 0 || typeof spec.command[0] !== "string") {
      continue;
    }
    const client = new StdioMcpClient(spec);
    try {
      await client.initialize();
      const tools = await client.listTools();
      clients.push(client);
      for (const tool of tools) {
        if (!tool || typeof tool.name !== "string") {
          continue;
        }
        pi.registerTool({
          name: bridgeToolName(spec.name, tool.name),
          label: spec.name + ":" + tool.name,
          description: (typeof tool.description === "string" && tool.description.length > 0
            ? tool.description
            : tool.name) + " (AICR tool " + tool.name + ")",
          parameters: Type.Unsafe(
            tool.inputSchema && typeof tool.inputSchema === "object" ? tool.inputSchema : { type: "object" },
          ),
          execute: async (_toolCallId, params) => {
            const result = await client.callTool(tool.name, params);
            const out = { content: [{ type: "text", text: toToolResultText(result) }] };
            if (result && result.isError === true) {
              out.isError = true;
            }
            return out;
          },
        });
      }
    } catch (error) {
      logBridgeError("server " + spec.name + " failed to initialize:", error);
      client.dispose();
    }
  }
}
`;
